# https://taskfile.dev

version: '3'

silent: true

includes:
  bootstrap: .taskfiles/Bootstrap.yaml

  context:
    aliases: [c]
    taskfile: .taskfiles/Context.yaml

  dive: .taskfiles/Dive.yaml

  docker:
    aliases: [d]
    taskfile: .taskfiles/Docker.yaml

  precommit:
    aliases: [pc]
    taskfile: .taskfiles/PreCommit.yaml

tasks:
  default:
    desc: List available tasks in this project
    cmds:
      - task -a
